FROM node:14

WORKDIR /var/node/twitter_clone_api

ENV ENV=development
ENV PORT=3000
ENV TYPEORM_CONNECTION=postgres
ENV TYPEORM_USERNAME=postgres
ENV TYPEORM_PASSWORD=admin
ENV TYPEORM_DATABASE=twitter
ENV TYPEORM_MIGRATIONS=migrations/*.ts
ENV TYPEORM_ENTITIES=src/models/*.ts
ENV TYPEORM_LOGGING=true
ENV TYPEORM_MIGRATIONS_RUN=true
ENV REDIS_PORT=6379

COPY . .

RUN yarn

CMD yarn dev
