version: "3"
services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - TYPEORM_HOST=database
      - REDIS_HOST=redis_server
    depends_on:
      - database
      - redis_server
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=twitter
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis_server:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
volumes:
  postgres_data:
  redis_data:
